sylius_twig_hooks:
    hooks:
        'sylius_admin.order.show.content.header.title_block.actions':
            refunds:
                template: '@SyliusRefundPlugin/admin/order/content/header/title_block/actions/refunds.html.twig'
                priority: -100

        'sylius_admin.order.show.content.sections.payments':
            refund_header:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/refund_header.html.twig'
                priority: -100
            refund_items:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/refund_items.html.twig'
                priority: -200

        'sylius_admin.order.show.content.sections.payments.item.actions':
            refund:
                enabled: false

        'sylius_admin.order.show.content.sections.payments.refund_header':
            title:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/header/title.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.payments.refund_item':
            state:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/item/state.html.twig'
                priority: 300
            name:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/item/name.html.twig'
                priority: 200
            amount:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/item/amount.html.twig'
                priority: 100
            actions:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/item/actions.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.payments.refund_item.actions':
            complete:
                template: '@SyliusRefundPlugin/admin/order/content/sections/payments/item/actions/complete.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections#left':
            credit_memos:
                template: '@SyliusRefundPlugin/admin/order/content/sections/credit_memos.html.twig'
                priority: 50

        'sylius_admin.order.show.content.sections.credit_memos':
            header:
                template: '@SyliusRefundPlugin/admin/order/content/sections/credit_memos/header.html.twig'
                priority: 100
            list:
                component: 'sylius_refund:admin:credit_memos'
                props:
                    order: '@=_context.order'
                    template: '@SyliusRefundPlugin/admin/order/credit_memo/list.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.credit_memos.header':
            title:
                template: '@SyliusRefundPlugin/admin/order/content/sections/credit_memos/header/title.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.credit_memos.list':
            details:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/details.html.twig'
                priority: 300
            channel:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/channel.html.twig'
                priority: 200
            total:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/total.html.twig'
                priority: 100
            actions:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/actions.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.credit_memos.list.details':
            date:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/details/date.html.twig'
                priority: 100
            number:
                template: '@SyliusRefundPlugin/admin/order/credit_memo/list/details/number.html.twig'
                priority: 0

        'sylius_admin.order.show.content.sections.credit_memos.list.actions':
            download:
                template: '@SyliusRefundPlugin/admin/order/content/sections/credit_memos/items/actions/download.html.twig'
                enabled: '%sylius_refund.pdf_generator.enabled%'
                priority: 0
