sylius_twig_hooks:
    hooks:
        'sylius_refund.admin.order.refund':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 200
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 100
            sections:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.header':
            breadcrumbs:
                template: '@SyliusRefundPlugin/admin/order/refund/content/header/breadcrumbs.html.twig'
                priority: 100
            title_block:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.header.title_block':
            title:
                template: '@SyliusRefundPlugin/admin/order/refund/content/header/title_block/title.html.twig'
                priority: 100
            actions:
                template: '@SyliusRefundPlugin/admin/order/refund/content/header/title_block/actions.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.header.title_block.actions':
            clear_all:
                template: '@SyliusRefundPlugin/admin/order/refund/content/header/title_block/actions/clear_all.html.twig'
                priority: 100
            refund_all:
                template: '@SyliusRefundPlugin/admin/order/refund/content/header/title_block/actions/refund_all.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections':
            form:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form.html.twig'
                priority: 100

        'sylius_refund.admin.order.refund.content.sections.form':
            items:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items.html.twig'
                priority: 200
            fields:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/fields.html.twig'
                priority: 100
            refunded_total:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/refunded_total.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.items':
            label:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/label.html.twig'
                priority: 100
            table:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.items.table':
            header:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/header.html.twig'
                priority: 100
            body:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.items.table.header':
            item_info:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/header/item_info.html.twig'
                priority: 300
            total:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/header/total.html.twig'
                priority: 200
            refund_value:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/header/refund_value.html.twig'
                priority: 100
            blank:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/header/blank.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.items.table.body':
            products:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/products.html.twig'
                priority: 0
            shipping:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/shipment.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.items.table.body.products':
            item_info:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/products/item_info.html.twig'
                priority: 300
            total:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/products/total.html.twig'
                priority: 200
            refund_value:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/products/refund_value.html.twig'
                priority: 100
            refund_button:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/items/table/body/products/refund_button.html.twig'
                priority: 0

        'sylius_refund.admin.order.refund.content.sections.form.fields':
            payment_method:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/fields/payment_method.html.twig'
                priority: 100
            comment:
                template: '@SyliusRefundPlugin/admin/order/refund/content/sections/form/fields/comment.html.twig'
                priority: 0
